export enum MONTH {
  ENERO = 'ENERO',
  FEBRERO = 'FEBRERO',
  MARZO = 'MARZO',
  ABRIL = 'ABRIL',
  MAYO = 'MAYO',
  JUNIO = 'JUNIO',
  JULIO = 'JULIO',
  AGOSTO = 'AGOSTO',
  SEPTIEMBRE = 'SEPTIEMBRE',
  OCTUBRE = 'OCTUBRE',
  NOVIEMBRE = 'NOVIEMBRE',
  DICIEMBRE = 'DICIEMBRE',
}


export const MONTH_INDEX: Record<MONTH, number> = {
  [MONTH.ENERO]: 0,
  [MONTH.FEBRERO]: 1,
  [MONTH.MARZO]: 2,
  [MONTH.ABRIL]: 3,
  [MONTH.MAYO]: 4,
  [MONTH.JUNIO]: 5,
  [MONTH.JULIO]: 6,
  [MONTH.AGOSTO]: 7,
  [MONTH.SEPTIEMBRE]: 8,
  [MONTH.OCTUBRE]: 9,
  [MONTH.NOVIEMBRE]: 10,
  [MONTH.DICIEMBRE]: 11,
};